### ISSUE TITLE
Not compatible with kirby-matomo plugin

### ISSUE THREAD

**Issue by MaluNoPeleke** [mauricerenck/komments#22]
I have installed Komments together with the [kirby-matomo plugin](https://github.com/sylvainjule/kirby-matomo) and the panel blueprint of the Matomo plugin doesn't work anymore after installing Komments.
The developer console shows the following error:

> Uncaught ReferenceError: $bhZj$exports is not defined
>     at index.js?1629713017:formatted:277
>     at index.js?1629713017:formatted:2609

Line 277 looks like this:

    var aa, Cb, ba, Ea = ga.MAX_SAFE_COMPONENT_LENGTH, Db = ($bhZj$exports = {}).re = aa = [], k = (Cb = []), x = (ba = {}), Eb = 0, z = function($, r, a) {

**Comment by mauricerenck** [comment]
Can you please tell me your kirby version and the version of both plugins? Then I can create a local test installation with that versions. On my website I use both plugins, too, and don't have any problems.

**Comment by mauricerenck** [comment]
That might be the cause, I am working on compatiblilty with 3.6, as the panel works very different regarding to plugins. If you disable matomo, the plugin works?

**Comment by MaluNoPeleke** [comment]
Yes, to some degree but without the dashboard or the kommentspending widget.
But in this issue the main problem is that Komments causes kirby-matomo to crash as described in the first post.

**Comment by mauricerenck** [comment]
Okay,

I'll keep this issue open and give an update here, as soon as I made progress regarding to Kirby 3.6.

**Comment by MaluNoPeleke** [comment]
Can be closed because of https://github.com/mauricerenck/komments/pull/23
