### ISSUE TITLE
Incompatible with Commentions plugin

### ISSUE THREAD

**Issue by MaluNoPeleke** [mauricerenck/komments#24]
After installing the latest Komments plugin via composer on a Kirby 3.6.0-rc.3 environment I just get an error 500 message for the panel and the website without any additional information in the browser console or the apache error log.
![image](https://user-images.githubusercontent.com/1446541/140031048-1744056a-1a1f-4824-bc2a-2bab9ef8d959.png)
(in the screenshot Komments is not listed because if it is installed I couldn't open the panel anymore).

**Comment by mauricerenck** [comment]
I cannot reproduce this issue. I tried the starterkit and updated it to k3.6-rc4.

Can you please retry with the latest version?

**Comment by MaluNoPeleke** [comment]
It still happens for me with Kirby 3.6.0-RC.4 and Komments 1.3.0 while I never had this problem with any other plugin before.
Maybe it is related to a combination of other installed plugins that you can see on the screenshot!?
Is there any way to debug it better? I cannot see any further error messages in the developer console or the Apache error log. Debugging is turned on in the Kirby config.

**Comment by mauricerenck** [comment]
Strange…
Depending on your system, it might help to run a php server in a terminal. Sometimes when 5xx errors occure you get more information directly in the terminal then. I don't know K3.6 still supports it, but you could try this in the root directory of your installation: `php -S localhost:8000 kirby/router.php`.

**Comment by MaluNoPeleke** [comment]
No option as I am running it on https://uberspace.de/

**Comment by mauricerenck** [comment]
Ah, so you don't have a local environment you're working on?

> Have you tried to install the plugins that I have installed?
No, not yet, I hoped I can avoid it, as you have a lot of them running ;) but then I'll probably install them step be step and have a look.

**Comment by mauricerenck** [comment]
could you copy and paste the list here as text? Then I dont have to type in everything manually from the screenshot.

**Comment by MaluNoPeleke** [comment]
beluga/navigation | Chris Martin | MIT | 2.1.2
bnomei/doctor | Bruno Meilick | MIT | 1.5.1
bnomei/feed | Bruno Meilick | MIT | 1.5.1
bnomei/fingerprint | Bruno Meilick | MIT | 3.0.14
bnomei/robots-txt | Bruno Meilick | MIT | 1.5.0
bvdputte/kirbyAutopublish | Bart Vandeputte | MIT | -
cookbook/block-factory | - | - | -
daandelange/simplestats | Daan de Lange | MIT | 0.4.3-beta
diesdasdigital/meta-knight | Jonathan Muth | BSD-3-Clause | -
flokosiol/focus | Flo Kosiol | MIT | 3.0.7
genxbe/instagram | Sam Serrien | MIT | -
hashandsalt/twitter | Hash&Salt | MIT | -
kirby-extended/highlighter | Johann Schopplich | MIT | -
kirbyzone/sitemapper | Kirbyzone | MIT | -
medienbaecker/autoresize | Thomas Günther | MIT | -
peleke/page-methods | - | - | -
rasteiner/k3-pagesdisplay-section | Roman Steiner | ISC | -
sgkirby/commentions | Sebastian Greger | MIT | 2.0.0-beta.4
sylvainjule/autofocus | Sylvain Julé | MIT | -
sylvainjule/matomo | Sylvain Julé | MIT | -
texnixe/k3-filesdisplay-section | Sonja Broda | MIT | 1.0.0
texnixe/similar | Sonja Broda | MIT | 2.0.0

**Comment by MaluNoPeleke** [comment]
> Ah, so you don't have a local environment you're working on?
> 
> > Have you tried to install the plugins that I have installed?
> > No, not yet, I hoped I can avoid it, as you have a lot of them running ;) but then I'll probably install them step be step and have a look.

Exactly, as I change devices regularly per day it is easier for me to work directly on the host where I want to deploy it to later.

**Comment by mauricerenck** [comment]
Okay, I got it.
You also installed commentions plugin. Both of our plugins use `mf2/mf2`. Sebastian includes it directly in his plugin, I use the indieweb/mention-client which has `mf2/mf2` as a dependency.

Both plugins try to declare the parser which causes `Cannot redeclare Mf2\parse()`

I probably can move the mention client to my indieconnector plugin as soon as I remove the send webmention functionality from the komments plugin. But if you want to receive webmentions, you have to install that plugin too, so…  It might be a good idea to investigate how to prevent his - what do you think @sgkirby ? Would it be a solution to not include the lib directly but to use the autoloader for that, Sebastian? I am not quite sure.

**Comment by MaluNoPeleke** [comment]
I wanted to evaluate the best comment system for my use cases and that's why I tried to install both at the same time. Would be great if that would be possible.

**Comment by mauricerenck** [comment]
I'll keep that in mind, maybe Sebastian has an idea how we can solve that conflict. In the long term the dependency will be removed from the komments plugin.

But as I would consider this an edge case, I will keep this issue open for now and will focus on my other plugins to get them up and running with K3.6. I hope that's understandable.

**Comment by MaluNoPeleke** [comment]
Sure, I can fully understand that. I was able to install Komments correctly after uninstalling Commentions and discovered some other issues (#30 #31 #32 #33)

**Comment by sebastiangreger** [comment]
> Both plugins try to declare the parser which causes `Cannot redeclare Mf2\parse()`

Good catch @mauricerenck :raised_hands:, that is indeed mostly due to Commentions not using autoload for that library.

> It might be a good idea to investigate how to prevent this - what do you think @sebastiangreger ? Would it be a solution to not include the lib directly but to use the autoloader for that, Sebastian? I am not quite sure.

I believe that's the solution, indeed: Commentions autoloading the Mf2 library should eliminate the issue. All I can currently find time for is a quickfix: I hacked the namespace of our statically loaded copy to be `Mf2c`, so the collision issue is gone with the [latest commit](https://github.com/sebastiangreger/kirby3-commentions/commit/61a12d7577724fa3d3358b5f9ecc704a2c10f17c) in the `develop` branch of Commentions, which should now play nicely with other IndieWeb-related plugins :slightly_smiling_face:

I created an issue for myself to eventually™ fix this properly…

**Comment by MaluNoPeleke** [comment]
Thanks for the quick response
