### ISSUE TITLE
Cannot publish comments from the global comment page

### ISSUE THREAD

**Issue by MaluNoPeleke** [mauricerenck/komments#31]
Right after installing Komments 1.3.0 on a Kirby 3.6.0-rc.4 build I get the following error message in the developer console after trying to publish a test comment (no change on the panel page visible):

> index.js:1 POST https://dev.domain.de/api/komments/publish 500
> request @ index.js:1
> post @ index.js:1
> publish @ index.js?1636570749:349
> click @ index.js?1636570749:349
> Vt @ vendor.js:6
> n @ vendor.js:6
> Vt @ vendor.js:6
> n @ vendor.js:6
> i._wrapper @ vendor.js:6
> index.js:1 {status: 'error', message: "Class 'mauricerenck\\Komments\\Exception' not found", code: 500, exception: 'Error', key: null, …}code: 500details: Array(0)length: 0[[Prototype]]: Array(0)exception: "Error"file: "../dev.domain.de/site/plugins/komments/utils/moderation.php"key: nullline: 143message: "Class 'mauricerenck\\Komments\\Exception' not found"route: "komments/publish"status: "error"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
> onError @ index.js:1
> request @ index.js:1
> await in request (async)
> post @ index.js:1
> publish @ index.js?1636570749:349
> click @ index.js?1636570749:349
> Vt @ vendor.js:6
> n @ vendor.js:6
> Vt @ vendor.js:6
> n @ vendor.js:6
> i._wrapper @ vendor.js:6
> komments:1 Uncaught (in promise) {status: 'error', message: "Class 'mauricerenck\\Komments\\Exception' not found", code: 500, exception: 'Error', key: null, …}code: 500details: []exception: "Error"file: "../dev.domain.de/site/plugins/komments/utils/moderation.php"key: nullline: 143message: "Class 'mauricerenck\\Komments\\Exception' not found"route: "komments/publish"status: "error"[[Prototype]]: Object
> Promise.then (async)
> publish @ index.js?1636570749:349
> click @ index.js?1636570749:349
> Vt @ vendor.js:6
> n @ vendor.js:6
> Vt @ vendor.js:6
> n @ vendor.js:6
> i._wrapper @ vendor.js:6

**Comment by mauricerenck** [comment]
The latest release should probably fix this particular error, but you might into other trouble, as that exception is thrown, when the page you want to publish the comment on is not found.

**Comment by MaluNoPeleke** [comment]
I think something went wrong with that fix because version 1.3.1 has no changes besides version number: https://github.com/mauricerenck/komments/commit/be3e5c944765f156c26c76611bf5fabbbc5cb126
I am still facing the issue with 1.3.3

**Comment by mauricerenck** [comment]
Yeah, that's a bit confusing, the release automation creates a new commit for a release, to set the version in the composer.json. The real changes are in here: https://github.com/mauricerenck/komments/commit/9ff17e301df0efffd67304a32f84cc7b3b1c8e0d

Do you still get the same error?

**Comment by MaluNoPeleke** [comment]
Yes:
![image](https://user-images.githubusercontent.com/1446541/141472683-0b3634cd-24c4-400d-8072-3c748c9536b2.png)

**Comment by mauricerenck** [comment]
Ah, I see. So this is no more the Exception Class not found error, but it doesn't find the page of the comment. Can you please provide the post body sent to the publish endpoint? There should be a pageSlug in there.

![Bildschirmfoto 2021-11-12 um 14 57 13](https://user-images.githubusercontent.com/964547/141478501-b6496154-b238-4c3c-b1f6-f5d8437a9e13.png)

**Comment by MaluNoPeleke** [comment]
![image](https://user-images.githubusercontent.com/1446541/141482646-4d7d8910-9a76-400c-ab21-292e60d5ea8f.png)

This is the corresponding URL on the panel: /panel/pages/blog+ressourcen-der-erde-verbraucht-wo-ist-die-nachste?language=de

**Comment by mauricerenck** [comment]
Thank you, so there is `blog/` missing in the page slug. I will investigate what's happening there.

**Comment by mauricerenck** [comment]
This is fixed with v1.3.4

**Comment by MaluNoPeleke** [comment]
Thanks, I can confirm
