### ISSUE TITLE
Komments Pending label not translatable

### ISSUE THREAD

**Issue by MaluNoPeleke** [mauricerenck/komments#32]
When trying to change the label of the Komments Pending Widget nothing happens with Komments 1.3.0:

          komments:
            type: fields
            fields:
              kommentsPending:
                type: kommentsPending
                label: Wartende Kommentare

![image](https://user-images.githubusercontent.com/1446541/141373795-f56aed5b-05b0-4653-909e-dd4465d40a03.png)

**Comment by mauricerenck** [comment]
Fixed in v1.3.3
