### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by MaluNoPeleke** [mauricerenck/komments#35]
Currently replies have an <ul> element outside of the <li> element which makes it hard to nest/indent. Could you change that to something like here: https://stackoverflow.com/questions/1172843/need-advice-on-html-css-structure-for-indented-threaded-comments/

**Comment by mauricerenck** [comment]
Have a look at this post: https://maurice-renck.de/en/projects/komments/custom-comments-design which also may help you with #34 I guess.

Changing the listing would be a breaking change for other users having their own styling, so I don't want to do this without some kind of announcement.

**Comment by MaluNoPeleke** [comment]
Thanks, that is indeed helpful and could be mentioned here on GitHub as well.
What is miss still is a reference for replies. If I click on "Answer" on a comment I see the name mentioned in the komment form field but when rendering the new comment (reply) there is no differentiation between a "normal" comment and a replied comment as far as I can see. How is it then possible to group/nest comments with replies?

**Comment by mauricerenck** [comment]
I probably will move those tips as docs to this repo.

In the comment form there is a hidden field `replyTo`. If you click on reply the field value of this field is filled with the id of the comment you want to reply to. This later on will be stored in `mentionOf` in the markdown file.

In the utils of this plugin there is the `parseKomments()` method which creates that nested structure. It's called in the listing snippet and does the magic.

**Comment by MaluNoPeleke** [comment]
Can you help me figure out how to group comments in threads and display them slightly indented (only one level, no further indentiation for more replies to replies)?

**Comment by mauricerenck** [comment]
I can send you an example of how I do this on my page. I'll ping you here.

**Comment by mauricerenck** [comment]
Here is my example: https://gist.github.com/mauricerenck/12d2edb6cc58c991ac7986f7ace8d25d
I removed some stuff, for example the likes etc. 

As you can see, I didn't modify a lot. Mostly added some classes and containers needed by the ui framework I use.
The nesting works because of the `addReply()` part, where `<ul>` tags are created for each nested level. By default `ul` has a padding on the left. So that does the magic.

So, what you could do if you only want the second level to have indentiation, is write some css for that, something like that: https://codepen.io/mauricerenck/pen/WNEPpdN

Which will remove the padding for all ul elements and then only adds a padding for the first child. If I understood you correct, this is what you wanted.

**Comment by MaluNoPeleke** [comment]
Thanks for your support and effort, this works for me as well.
One follow-up question: How would it be possible to show the @repliedname after the author-action div?
This would visually help to understand the connection.

**Comment by mauricerenck** [comment]
I am not quite sure, what you mean. In general you can move `<span class="replyHandleDisplay"></span>` wherever you want as long as it is a child of `#kommentform`.

**Comment by MaluNoPeleke** [comment]
I want to display it for individual replies as well that's why I added it to the snippets/komments/type/reply.php file like this but it doesn't appear:

```
...
    <div class="author-action">
        <?php if ($komment['verified'] == 'true') : ?><span class="verified-badge"><?php echo option('mauricerenck.komments.komment-icon-verified', '✅'); ?></span><?php endif; ?>
        <a href="<?php echo $komment['authorurl']; ?>" rel="nofollow" target="_blank"><?php echo $komment['author']; ?></a>&nbsp;
        <span class="replyHandleDisplay"></span>
        <!--<?php echo t('mauricerenck.komments.replied'); ?>-->
        <span class="date float-right"><?php echo "(" . $komment['published']->published()->toDate('%d.%m.%Y %H:%M') . ")"; ?></span>
    </div>
...
```

**Comment by mauricerenck** [comment]
Ah I see.

This won't work actually. The reply handle will only be filled on click and only the first one found will be filled. What you want to do is not possible currently, at least without some fair amount of coding, as the reply handle isn't saved with the comment, only the id of the comment replying to is stored.

But this would be indeed a nice feature. I will add it to the list. It shouldn't be to much work, to implement it.

**Comment by MaluNoPeleke** [comment]
Thanks, that would be great

**Comment by MaluNoPeleke** [comment]
One further question: how to display the reply/web mention icon below the author avatar instead of a dedicated column?
