### ISSUE TITLE
outbox.json file after saving

### ISSUE THREAD

**Issue by alexanderhacke** [mauricerenck/komments#41]
I found a crazy thing in the plugin.

If I change a simple text on any page in the panel and then click save, I see a file named outbox.json in the files section.
This only happens on listed (public) sites.

My website runs on PHP8. I have not installed any other plugins.
I have the same thing when i try to you use your plugin with the kirby starterkit
Do you possibly know what this is related to?

**Comment by mauricerenck** [comment]
Hey,

you found a feature ;)

Currently the komments plugin is able to send webmentions if you enable it in your config.php. Komments looks for URLs in the content and sends a webmention if enabled. To not spam the sites mentioned it creates the outbox.json and in there stores the URLs which already have been pinged.

It would be better to not create that file, if sending webmentions is disabled, but this functionality will be removed in one of the upcoming releases and be part of the IndieConnector plugin. So at this point it's a "won't fix" for me, it'll be automatically solved soon. 

It's nothing to worry on your side, but I understand it can be annoying. Hopefully I'll be able to publish the mentioned changes soon.
