### ISSUE TITLE
formFeedback not working

### ISSUE THREAD

**Issue by Fluxium2006** [mauricerenck/komments#42]
Using version 1.5.1 of this plugin together with Kirby 3.6.1 gives a `JSON.parse` error upon submitting a comment.
The comment gets submitted and I'm able to review it in the dashboard, but the form feedback element `div.form-feedback` doesn't work as no text appears and the class `.moderation-note` doesn't get added.

I could fix this problem.

In `komments/utils/receiveKomment.php`, line 165, I changed the following:

Before (not working)
`public function sendReponseToClient(string $headlineTranslationString, string $messageTranslationString, number $httpCode, boolean $shouldReturnJson)`

After (working)
`public function sendReponseToClient(string $headlineTranslationString, string $messageTranslationString, number $httpCode, bool $shouldReturnJson)`

**Comment by mauricerenck** [comment]
Can you please tell me, which PHP version you are using?

**Comment by Fluxium2006** [comment]
I'm using PHP 8.0.2 and XAMPP for local development.

**Comment by mauricerenck** [comment]
A fix for this is included in https://github.com/mauricerenck/komments/releases/tag/v1.5.2
Can you please confirm?

**Comment by Fluxium2006** [comment]
Works perfectly!

**Comment by mauricerenck** [comment]
Great :) thank you for letting me know!
