### ISSUE TITLE
Use in headless setup

### ISSUE THREAD

**Issue by thebraunfox** [mauricerenck/komments#47]
Hi Maurice, 

I'm running Kirby 3.6 as headless CMS with Nuxt.js and I was wondering if there is a way I can send comments from the frontend to Kirby using your Plugin? 

Does the plugin offers an endpoint where I could send the formData? or is there any other way this could work?

Thank you for your great plugins!

Best,
Juan

**Comment by mauricerenck** [comment]
Hey Juan,

thank you for the kind words :)

Yes, you can do that. The plugin is already using JavaScript for sending comments to kirby, the regular form action is a fallback only.

There is a `POST` endpoint available under `/komments/send` which takes the form values as body. So you can steal the form from the snippet in `snippets/kommentform.php`. And have a look at the JS file in `assets/komments.js`. Be aware that there are two hidden fields which are used for spam protection, so don't forget to add them, even if they aren't visible.

There is currently no api endpoint for getting the comment list, but I guess you'll do that on build time.  The comments are  stored in a structured field. I would recommend to use `$komments = $kommentUtils->parseKomments($page->kommentsInbox());` as you can see in `snippets/webmention-splitted.php`. 

It may be that I will switch from structured field to sqlite in the future, so using `$kommentUtils->parseKomments()`; will ensure that your comments show up even if their storage might be changed. 

Let me know if there are any problems or questions.

Best,
Maurice

**Comment by thebraunfox** [comment]
Hi Maurice,

Great, thanks for the prompt and detailed answer. I'll give it a try and I'll let you know how it went. 

Best,
Juan
