### ISSUE TITLE
see commentors email so can respond personally

### ISSUE THREAD

**Issue by jklue** [mauricerenck/komments#57]
Is there a way to see the commenter's email address? They asked a question on our blog and we wanted to answer them personally. Thank you!

**Comment by mauricerenck** [comment]
The email addresses are currently not stored. They are hashed and part of the gravatar-url. I can add this as an optional feature, but unfortunately this won't help you in this case.

You could try to use some tools to decode the md5 hash, but that normally won't work very well.
