### ISSUE TITLE
panel area not working with kirby 4

### ISSUE THREAD

**Issue by movingwater** [mauricerenck/komments#61]
The komments plugin is working fine on the frontend. But the panel area is broken. If want to view it I get redirected to `myurl.test/api/komments/queued` and the following message appears:
```
{
"status": "error",
"message": "Unauthenticated",
"code": 401,
"exception": "Kirby\\Exception\\AuthException",
"key": "error.auth",
"file": "authentication.php",
"line": 14,
"details": [],
"route": "komments/queued"
}
```

**Comment by mauricerenck** [comment]
Thank you for the feedback.
A K4 version is in the making, will hopefully be avail soon!
