### ISSUE TITLE
Pending Messages being shown on pages as if they were already approved

### ISSUE THREAD

**Issue by drackmas** [mauricerenck/komments#67]
I am using Kirby 4 with the Zero One theme. 

I installed Komments with composer.

In config I have:
    'mauricerenck.komments.komment-auto-publish' => false,
    'mauricerenck.komments.auto-publish-verified' => false,
    'mauricerenck.komments.webmention-auto-publish' => false,

I put the css snippet in header per instructions.  
<?php echo css(['/media/plugins/mauricerenck/komments/komments.css']); ?>

Then placed the other two snippets lower in the template for the comments.
<?php snippet('komments/kommentform'); ?>
<?php snippet('komments/webmention-splitted'); ?>

In my article blueprint I added:
sections:
    komments:
        extends: sections/komments

When I open the article in the panel I can see that the messages are only pending and not approved, but when I view the main website the pending messages are still shown.

The main Komments tab from within the panel has not had any pending comments show up on it at all.

**Comment by drackmas** [comment]
I did the same steps only instead of using composer I downloaded the zip file and manually placed in plugin folder.

I'm still seeing the pending messages on the public blog posts. I am able to see the pending messages in the Komments tab in the panel now.

I'm not exactly sure what is going on.

**Comment by mauricerenck** [comment]
This sounds like a bug. I will have a look at it any come back to you, if I need more information.

**Comment by mauricerenck** [comment]
Please update to version [2.0.5](https://github.com/mauricerenck/komments/releases/tag/v2.0.5) - this release should fix the bug. Thank you for reporting it! Could you please confirm that this helped?

**Comment by drackmas** [comment]
Thank you. Confirmed that it fixed the issue. I tested with both composer and installing it manually. Thank you for the update!
